USE basic_query;
SELECT
    B.AGRDE_SE_CD,
    B.AGRDE_POPLTN_CNT,
    CONCAT(ROUND((B.AGRDE_POPLTN_CNT / B.SUM_AGRDE_POPLTN_CNT) * 100, 2), "%") AS "인구비율"
FROM
    (SELECT A.AGRDE_SE_CD,
            A.AGRDE_POPLTN_CNT,
            SUM(A.AGRDE_POPLTN_CNT) OVER () AS SUM_AGRDE_POPLTN_CNT
     FROM (SELECT A.AGRDE_SE_CD,
                  SUM(A.POPLTN_CNT) AS AGRDE_POPLTN_CNT
           FROM TB_POPLTN A
           WHERE A.ADMINIST_ZONE_NO LIKE '__00000000'
             AND A.POPLTN_SE_CD = 'T'
             AND A.STD_MT = '202304'
           GROUP BY A.AGRDE_SE_CD
           ORDER BY A.AGRDE_SE_CD) A
     ) B;
     
     
     
-- 05 연령대별 인구가 가장 많은 지역

SELECT
    A.AGRDE_SE_CD,
    A.ADMINIST_ZONE_NO,
    A.ADMINIST_ZONE_NM,
    A.POPLTN_CNT
FROM TB_POPLTN A
WHERE A.ADMINIST_ZONE_NO NOT LIKE '_____00000'
  AND A.POPLTN_SE_CD = 'T'
  AND A.POPLTN_CNT > 0
  AND A.STD_MT = '202304'
ORDER BY POPLTN_CNT DESC;


SELECT
		B.AGRDE_SE_CD,
		B.ADMINIST_ZONE_NO,
		B.ADMINIST_ZONE_NM,
		B.POPLTN_CNT,
		B.RNUM
FROM(
		SELECT
		    A.AGRDE_SE_CD,
		    A.ADMINIST_ZONE_NO,
		    A.ADMINIST_ZONE_NM,
		    A.POPLTN_CNT,
		    ROW_NUMBER() OVER (PARTITION BY A.AGRDE_SE_CD ORDER BY A.POPLTN_CNT DESC) AS RNUM
		FROM
				(
						SELECT
								A.AGRDE_SE_CD,
								A.ADMINIST_ZONE_NO,
								A.ADMINIST_ZONE_NM,
								A.POPLTN_CNT
						FROM TB_POPLTN A
						WHERE A.ADMINIST_ZONE_NO NOT LIKE '_____00000'
							AND A.POPLTN_SE_CD = 'T'
							AND A.POPLTN_CNT > 0
							AND A.STD_MT = '202304'
						ORDER BY POPLTN_CNT DESC
				) A
	) B
WHERE B.RNUM = 1 OR B.RNUM = 2
ORDER BY B.AGRDE_SE_CD;

-- 06. 연령대별 인구비율이 가장 높은 지역

SELECT
    D.AGRDE_SE_CD,
    D.ADMINIST_ZONE_NO,
    D.ADMINIST_ZONE_NM,
    D.POPLTN_CNT,
    D.POP_RATIO_BY_ADMINIST_ZONE
FROM (SELECT C.AGRDE_SE_CD,
             C.ADMINIST_ZONE_NO,
             C.ADMINIST_ZONE_NM,
             C.POPLTN_CNT,
             C.POP_RATIO_BY_ADMINIST_ZONE,
             ROW_NUMBER() OVER (PARTITION BY C.AGRDE_SE_CD ORDER BY C.POP_RATIO_BY_ADMINIST_ZONE DESC) AS RNUM
      FROM (SELECT B.AGRDE_SE_CD,
                   B.ADMINIST_ZONE_NO,
                   B.ADMINIST_ZONE_NM,
                   B.POPLTN_CNT,
                   ROUND(B.POPLTN_CNT / SUM(B.POPLTN_CNT) OVER (PARTITION BY B.ADMINIST_ZONE_NO),
                         2) AS "POP_RATIO_BY_ADMINIST_ZONE"
            FROM (SELECT A.AGRDE_SE_CD,
                         A.ADMINIST_ZONE_NO,
                         A.ADMINIST_ZONE_NM,
                         A.POPLTN_CNT
                  FROM TB_POPLTN A
                  WHERE A.ADMINIST_ZONE_NO NOT LIKE '_____00000'
                    AND A.POPLTN_SE_CD = 'T'
                    AND A.POPLTN_CNT > 0
                    AND A.STD_MT = '202304'
                  ORDER BY POPLTN_CNT DESC) B)
          C)
    D
WHERE D.RNUM = 1;

-- 숙제
-- 07. 남성보다 여성의 수가 가장 많은 지역 구하기
-- 전국의 각 읍/면/동 기준 남성의 수보다 여성의 수가 가장 많은 지역을 구한다.
SELECT
		B.ADMINIST_ZONE_NO,
		B.ADMINIST_ZONE_NM,
		MAX(B.FEMALE_CNT) AS FEMALE_CNT,
		MAX(B.MALE_CNT) AS MALE_CNT,
		(MAX(B.FEMALE_CNT) - MAX(B.MALE_CNT)) AS DIFF
FROM(
		SELECT
				A.ADMINIST_ZONE_NO,
				A.ADMINIST_ZONE_NM,
				A.POPLTN_SE_CD,
				CASE WHEN A.POPLTN_SE_CD = 'F' THEN SUM(A.POPLTN_CNT) ELSE 0 END AS FEMALE_CNT,
				CASE WHEN A.POPLTN_SE_CD = 'M' THEN SUM(A.POPLTN_CNT) ELSE 0 END AS MALE_CNT
		FROM TB_POPLTN A
		WHERE A.ADMINIST_ZONE_NO NOT LIKE '_____00000'
			AND (A.POPLTN_SE_CD = 'M' OR A.POPLTN_SE_CD = 'F')
			AND A.POPLTN_CNT > 0
		GROUP BY A.ADMINIST_ZONE_NM, A.POPLTN_SE_CD, ADMINIST_ZONE_NO
	) B
GROUP BY B.ADMINIST_ZONE_NM, B.ADMINIST_ZONE_NO
ORDER BY DIFF DESC LIMIT 1;



-- 08. 남성/여성 비율이 가장 높은 지역과 가장 낮은 지역 구하기
-- 전국의 각 읍/면/동 기준 남성 비율 및 여성 비율이 가장 높은 지역 구하기.

SELECT
		B.ADMINIST_ZONE_NO,
		B.ADMINIST_ZONE_NM,
		MAX(B.FEMALE_CNT) AS FEMALE_CNT,
		MAX(B.MALE_CNT) AS MALE_CNT,
		ROUND((MAX(B.FEMALE_CNT) / MAX(B.MALE_CNT)), 2) AS DIFF_RATIO
FROM(
		SELECT
				A.ADMINIST_ZONE_NO,
				A.ADMINIST_ZONE_NM,
				A.POPLTN_SE_CD,
				CASE WHEN A.POPLTN_SE_CD = 'F' THEN SUM(A.POPLTN_CNT) ELSE 0 END AS FEMALE_CNT,
				CASE WHEN A.POPLTN_SE_CD = 'M' THEN SUM(A.POPLTN_CNT) ELSE 0 END AS MALE_CNT
		FROM TB_POPLTN A
		WHERE A.ADMINIST_ZONE_NO NOT LIKE '_____00000'
			AND (A.POPLTN_SE_CD = 'M' OR A.POPLTN_SE_CD = 'F')
			AND A.POPLTN_CNT > 0
		GROUP BY A.ADMINIST_ZONE_NM, A.POPLTN_SE_CD, ADMINIST_ZONE_NO
	) B
GROUP BY B.ADMINIST_ZONE_NM, B.ADMINIST_ZONE_NO
ORDER BY DIFF_RATIO DESC;


SELECT C.*
FROM(
		SELECT
				B.ADMINIST_ZONE_NO,
				B.ADMINIST_ZONE_NM,
				MAX(B.FEMALE_CNT) AS FEMALE_CNT,
				MAX(B.MALE_CNT) AS MALE_CNT,
				ROUND((MAX(B.FEMALE_CNT) / MAX(B.MALE_CNT)), 2) AS DIFF_RATIO
		FROM(
				SELECT
						A.ADMINIST_ZONE_NO,
						A.ADMINIST_ZONE_NM,
						A.POPLTN_SE_CD,
						CASE WHEN A.POPLTN_SE_CD = 'F' THEN SUM(A.POPLTN_CNT) ELSE 0 END AS FEMALE_CNT,
						CASE WHEN A.POPLTN_SE_CD = 'M' THEN SUM(A.POPLTN_CNT) ELSE 0 END AS MALE_CNT
				FROM TB_POPLTN A
				WHERE A.ADMINIST_ZONE_NO NOT LIKE '_____00000'
					AND (A.POPLTN_SE_CD = 'M' OR A.POPLTN_SE_CD = 'F')
					AND A.POPLTN_CNT > 0
				GROUP BY A.ADMINIST_ZONE_NM, A.POPLTN_SE_CD, ADMINIST_ZONE_NO
			) B
		GROUP BY B.ADMINIST_ZONE_NM, B.ADMINIST_ZONE_NO
	) C
WHERE C.DIFF_RATIO = (SELECT MAX(C.DIFF_RATIO))
ORDER BY DIFF_RATIO DESC;

-- ----------
SELECT * 
FROM 
   (
      SELECT 
         A.ADMINIST_ZONE_NM,
         SUM(CASE WHEN A.POPLTN_SE_CD = 'F' THEN A.POPLTN_CNT ELSE 0 END) AS FEMALE_COUNT,
         SUM(CASE WHEN A.POPLTN_SE_CD = 'M' THEN A.POPLTN_CNT ELSE 0 END) AS MALE_COUNT,
         CONCAT(ROUND(SUM(CASE WHEN A.POPLTN_SE_CD = 'F' THEN A.POPLTN_CNT ELSE 0 END) / 
            (SUM(A.POPLTN_CNT)) * 100, 2), '%') AS FEMALE_RATIO,
         CONCAT(ROUND(SUM(CASE WHEN A.POPLTN_SE_CD = 'M' THEN A.POPLTN_CNT ELSE 0 END) / 
            (SUM(A.POPLTN_CNT)) * 100, 2), '%') AS MALE_RATIO,
         ROW_NUMBER() OVER(ORDER BY SUM(CASE WHEN A.POPLTN_SE_CD = 'F' THEN A.POPLTN_CNT ELSE 0 END) / 
            (SUM(A.POPLTN_CNT)) DESC) AS FE_ROW_NUM,
         ROW_NUMBER() OVER(ORDER BY SUM(CASE WHEN A.POPLTN_SE_CD = 'M' THEN A.POPLTN_CNT ELSE 0 END) / 
            (SUM(A.POPLTN_CNT)) DESC) AS M_ROW_NUM
      FROM TB_POPLTN A
      WHERE 
         A.ADMINIST_ZONE_NO NOT LIKE '_____00000'
         AND A.POPLTN_SE_CD IN ('M', 'F')
         AND A.STD_MT = '202304'
      GROUP BY A.ADMINIST_ZONE_NM
   ) B
WHERE FE_ROW_NUM = 1 OR M_ROW_NUM = 1;