USE basic_query;

SHOW TABLES;

CREATE TABLE TB_TEMPER
(
	STD_DE VARCHAR(8),
	AREA_CD VARCHAR(3),
	AVG_TEMPER DECIMAL(3, 1),
	MIN_TEMPER DECIMAL(3, 1),
	MAX_TEMPER DECIMAL(3, 1),
	PRIMARY KEY (STD_DE, AREA_CD)
);

SELECT COUNT(*) FROM TB_TEMPER_DATA WHERE AREA_CD IS NULL;
DELETE FROM TB_TEMPER_DATA WHERE AREA_CD IS NULL;

INSERT INTO TB_TEMPER
SELECT
	REPLACE(STD_DE, '-', '') AS STD_DE,
	AREA_CD,
	AVG_TEMPER,
	MIN_TEMPER,
	MAX_TEMPER
FROM TB_TEMPER_DATA;

COMMIT;

SELECT * FROM TB_TEMPER;